version: '3'
services:
  mongodb:
    image: bitnami/mongodb:latest
    networks:
    - backend
  app:
    build: . 
    networks:
    - backend
    ports:
    - 8080:8080
    environment:
    - RACK_ENV=staging
   


networks:
  backend:
    driver: bridge
