# File: .github/workflows/workflow.yml
on: [push]

name: deploy okteto lecid

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master


    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

#    - uses: okteto/context@latest
#      with:
#        token: ${{ secrets.OKTETO_TOKEN }}
#        namespace: lecid
      
    - name: "Build"
      uses: okteto/build@latest
      with:
        tag: registry.cloud.okteto.net/lecid/kube-mongo-ruby:${{ github.sha }}

    - uses: danielr1996/envsubst-action@1.0.0
      env:
        VERSION: ${{ github.sha }}
        REPLICAS: 3
      with:
        input: k8s.template
        output: k8s.yml
    
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        namespace: lecid

    - name: "Create deployment"
      uses: okteto/apply@master
      with:
        manifest: k8s.yml
