# File: .github/workflows/workflow.yml
on: [push]

name: deploy okteto lecid

jobs:

  deploy-app:
    runs-on: ubuntu-latest
    container: okteto/okteto:2.0.1
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: deploy
        run: |
          okteto login --token ${{ secrets.OKTETO_TOKEN }}
          okteto build --progress plain -t registry.cloud.okteto.net/lecid/kube-mongo-ruby:${{ github.sha }} -f Dockerfile .
          export APP_VERSION=${{ github.sha }}
          export APP_REPLICAS= 3
          apk add envsubst
          envsubst < k8s.template > k8s.yml
          okteto namespace lecid
          okteto kubeconfig
          kubectl apply -f k8s.yml

